---

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev

      - name: Install mise dependencies
        uses: jdx/mise-action@v2

      - name: Run tests
        run: |
          nvim --version
          make test
